<a href="https://colab.research.google.com/github/AdwaaNasser/Saudi-Real-Estate-Market-Analysis/blob/main/Copy_of_01_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/drive/MyDrive/Transactions sale for real estate CSV.csv")

In [ ]:
#نظره سريعه للبيانات
print(df.info())
print(df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34664 entries, 0 to 34663
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   المنطقة               34664 non-null  object
 1   المدينة               34664 non-null  object
 2   المدينة / الحي        34664 non-null  object
 3   الرقم المرجعي للصفقة  34664 non-null  int64
 4   تاريخ الصفقة ميلادي   34664 non-null  object
 5   تاريخ الصفقة هجري     34664 non-null  object
 6   تصنيف العقار          34664 non-null  object
 7   عدد العقارات          34664 non-null  int64
 8   السعر                 34664 non-null  object
 9   المساحة               34664 non-null  object
dtypes: int64(2), object(8)
memory usage: 2.6+ MB
None
(34664, 10)

In [ ]:
df.head()

,المنطقة,المدينة,المدينة / الحي,الرقم المرجعي للصفقة,تاريخ الصفقة ميلادي,تاريخ الصفقة هجري,تصنيف العقار,عدد العقارات,السعر,المساحة
0,منطقة مكة المكرمه,الطائف,الطائف/ الكدى,35983585,2026/04/01,1447/10/13,سكني,1,"1,000,000",593.75
1,منطقة الرياض,حوطة بني تميم,حوطة بني تميم/ الورود,35979045,2026/04/01,1447/10/13,سكني,1,"1,115,626",575.00
2,منطقة مكة المكرمه,الطائف,الطائف/ الحلقة الشرقية,35986850,2026/04/01,1447/10/13,سكني,1,"600,000",307.74
3,منطقة مكة المكرمه,الطائف,الطائف/ اليمانيه,35984449,2026/04/01,1447/10/13,سكني,1,"245,000",179.79
4,منطقة الرياض,الدلم,الدلم/ الفيصلية,35972886,2026/04/01,1447/10/13,سكني,1,"120,000",500.00

In [ ]:
#القيم الناقصه
null= df.isna().sum()
null

المنطقة                 0
المدينة                 0
المدينة / الحي          0
الرقم المرجعي للصفقة    0
تاريخ الصفقة ميلادي     0
تاريخ الصفقة هجري       0
تصنيف العقار            0
عدد العقارات            0
السعر                   0
المساحة                 0
dtype: int64

In [ ]:
#المكرر
dup = df.duplicated().sum()
dup

np.int64(0)

In [ ]:
#أنواع الأعمده
df.dtypes

المنطقة                 object
المدينة                 object
المدينة / الحي          object
الرقم المرجعي للصفقة     int64
تاريخ الصفقة ميلادي     object
تاريخ الصفقة هجري       object
تصنيف العقار            object
عدد العقارات             int64
السعر                   object
المساحة                 object
dtype: object

In [ ]:
#القيم الشاذه
df.describe()

       الرقم المرجعي للصفقة  عدد العقارات
count          3.466400e+04  34664.000000
mean           3.689595e+07      1.014742
std            5.571971e+05      0.303337
min            3.430452e+07      1.000000
25%            3.642046e+07      1.000000
50%            3.685501e+07      1.000000
75%            3.740899e+07      1.000000
max            3.790381e+07     18.000000

In [ ]:
#تنظيف المسافات الزائده من الأعمده النصيه
df = df.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
#ازاله الصفوف المكرره
#سبب القرار : تم حذف المكررات لتجنب تكرارر سجلات الصفقات العقاريه
df = df.drop_duplicates()

In [1]:
plt.boxplot(df)

NameError: name 'plt' is not defined

In [ ]:
"""
ملخص عمليه التنظيف :
-الصفوف قبل التنظيف :34664
-الصفوف بعد التنظيف : 34663
سبب الحذف: حذف الصفوف المكرره.
"""

#حفظ البيانات المنظفه بالشكل المطلوب للمستودع
df.to_csv('clean.csv', index=False)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).